export const mockData = {
  dashboardStats: {
    activeJobs: 24,
    smsResponseRate: '94%',
    techUtilization: '87%',
    customerSatisfaction: '4.8/5',
  },
  workOrders: [
    {
      id: '1',
      workOrderNumber: '1234',
      title: 'AC Repair',
      description: 'AC not cooling properly, possible refrigerant leak',
      customer: {
        id: '1',
        name: 'John Smith',
        email: 'john@example.com',
        phone: '(555) 123-4567',
        address: '123 Main St, Anytown, USA',
      },
      technician: {
        id: '1',
        name: 'Mike Johnson',
        email: 'mike@speedyhvac.com',
        phone: '(555) 987-6543',
        status: 'On Site',
      },
      equipment: {
        id: '1',
        name: 'AC Unit',
        model: 'Carrier Infinity 24VNA9',
        serialNumber: 'CAR123456789',
        manufacturer: 'Carrier',
        type: 'Air Conditioner',
      },
      serviceType: 'Repair',
      priority: 'High',
      status: 'On Site',
      scheduledStart: '2025-07-19T14:00:00',
      scheduledEnd: '2025-07-19T16:00:00',
      actualStart: '2025-07-19T14:15:00',
      estimatedHours: 2,
      emergency: false,
      createdAt: '2025-07-19T09:30:00',
    },
    {
      id: '2',
      workOrderNumber: '1235',
      title: 'Heating Service',
      description: 'Annual maintenance for heating system',
      customer: {
        id: '2',
        name: 'Sarah Johnson',
        email: 'sarah@example.com',
        phone: '(555) 234-5678',
        address: '456 Oak Ave, Anytown, USA',
      },
      technician: {
        id: '3',
        name: 'Tom Wilson',
        email: 'tom@speedyhvac.com',
        phone: '(555) 876-5432',
        status: 'En Route',
      },
      equipment: {
        id: '2',
        name: 'Furnace',
        model: 'Trane XC95m',
        serialNumber: 'TRN987654321',
        manufacturer: 'Trane',
        type: 'Furnace',
      },
      serviceType: 'Maintenance',
      priority: 'Medium',
      status: 'Scheduled',
      scheduledStart: '2025-07-19T16:30:00',
      scheduledEnd: '2025-07-19T18:30:00',
      estimatedHours: 2,
      emergency: false,
      createdAt: '2025-07-18T15:45:00',
    },
    {
      id: '3',
      workOrderNumber: '1236',
      title: 'Maintenance',
      description: 'Quarterly maintenance check',
      customer: {
        id: '3',
        name: 'Mike\'s Restaurant',
        email: 'mike@restaurant.com',
        phone: '(555) 345-6789',
        address: '789 Elm St, Anytown, USA',
      },
      technician: null,
      equipment: {
        id: '3',
        name: 'Commercial AC',
        model: 'Lennox ML14XC1',
        serialNumber: 'LEN123987456',
        manufacturer: 'Lennox',
        type: 'Air Conditioner',
      },
      serviceType: 'Maintenance',
      priority: 'Low',
      status: 'Pending',
      scheduledStart: '2025-07-20T10:00:00',
      scheduledEnd: '2025-07-20T12:00:00',
      estimatedHours: 2,
      emergency: false,
      createdAt: '2025-07-18T09:15:00',
    },
  ],
  technicians: [
    {
      id: '1',
      name: 'Mike Johnson',
      email: 'mike@speedyhvac.com',
      phone: '(555) 987-6543',
      status: 'On Site',
      skills: ['AC Repair', 'Installation', 'Maintenance'],
      hourlyRate: 45,
      active: true,
      currentLocation: '123 Main St, Anytown, USA',
      currentJob: '1234',
    },
    {
      id: '2',
      name: 'Lisa Chen',
      email: 'lisa@speedyhvac.com',
      phone: '(555) 876-5432',
      status: 'Available',
      skills: ['Heating', 'Maintenance', 'Electrical'],
      hourlyRate: 42,
      active: true,
      currentLocation: 'Office',
      currentJob: null,
    },
    {
      id: '3',
      name: 'Tom Wilson',
      email: 'tom@speedyhvac.com',
      phone: '(555) 765-4321',
      status: 'En Route',
      skills: ['AC Repair', 'Heating', 'Installation'],
      hourlyRate: 40,
      active: true,
      currentLocation: 'En route to 456 Oak Ave',
      currentJob: '1235',
    },
  ],
  customers: [
    {
      id: '1',
      name: 'John Smith',
      email: 'john@example.com',
      phone: '(555) 123-4567',
      address: '123 Main St, Anytown, USA',
      city: 'Anytown',
      state: 'CA',
      zip: '12345',
      type: 'Residential',
      active: true,
    },
    {
      id: '2',
      name: 'Sarah Johnson',
      email: 'sarah@example.com',
      phone: '(555) 234-5678',
      address: '456 Oak Ave, Anytown, USA',
      city: 'Anytown',
      state: 'CA',
      zip: '12345',
      type: 'Residential',
      active: true,
    },
    {
      id: '3',
      name: 'Mike\'s Restaurant',
      email: 'mike@restaurant.com',
      phone: '(555) 345-6789',
      address: '789 Elm St, Anytown, USA',
      city: 'Anytown',
      state: 'CA',
      zip: '12345',
      type: 'Commercial',
      active: true,
    },
  ],
  messages: [
    {
      id: '1',
      sender: {
        id: '1',
        name: 'John Smith',
        type: 'customer',
      },
      content: 'When will the tech arrive?',
      type: 'SMS',
      direction: 'Inbound',
      sentAt: '2025-07-19T13:30:00',
      read: false,
    },
    {
      id: '2',
      sender: {
        id: '2',
        name: 'Sarah Johnson',
        type: 'customer',
      },
      content: 'Thanks for the quick service!',
      type: 'SMS',
      direction: 'Inbound',
      sentAt: '2025-07-19T13:15:00',
      read: false,
    },
    {
      id: '3',
      sender: {
        id: '3',
        name: 'Mike\'s Restaurant',
        type: 'customer',
      },
      content: 'Emergency AC failure',
      type: 'SMS',
      direction: 'Inbound',
      sentAt: '2025-07-19T12:30:00',
      read: false,
    },
  ],
  technicianMobile: {
    technician: {
      id: '1',
      name: 'Mike Johnson',
      email: 'mike@speedyhvac.com',
      phone: '(555) 987-6543',
      status: 'On Site',
    },
    currentJob: {
      id: '1',
      workOrderNumber: '1234',
      title: 'AC Repair',
      customer: {
        id: '1',
        name: 'John Smith',
        address: '123 Main St, Anytown, USA',
        phone: '(555) 123-4567',
      },
      status: 'On Site',
      startTime: '2025-07-19T14:15:00',
      elapsedTime: '1h 23m',
      progress: 70,
    },
    todaysJobs: [
      {
        id: '1',
        workOrderNumber: '1234',
        customer: {
          id: '1',
          name: 'John Smith',
          address: '123 Main St, Anytown, USA',
        },
        timeSlot: '2:00 PM - 4:00 PM',
        serviceType: 'AC Repair',
        status: 'In Progress',
      },
      {
        id: '2',
        workOrderNumber: '1235',
        customer: {
          id: '2',
          name: 'Sarah Johnson',
          address: '456 Oak Ave, Anytown, USA',
        },
        timeSlot: '4:30 PM - 6:30 PM',
        serviceType: 'Heating Service',
        status: 'Scheduled',
      },
    ],
    messages: [
      {
        id: '1',
        sender: {
          id: '1',
          name: 'John Smith',
          type: 'customer',
        },
        content: 'Hi, my AC stopped working this morning',
        sentAt: '2025-07-19T13:45:00',
        direction: 'Inbound',
      },
      {
        id: '2',
        sender: {
          id: '1',
          name: 'Mike Johnson',
          type: 'technician',
        },
        content: 'I\'m on my way! ETA 15 minutes.',
        sentAt: '2025-07-19T13:50:00',
        direction: 'Outbound',
      },
    ],
  },
};